package loopwork.backend.client;

import jakarta.persistence.*;
import loopwork.backend.professional.Professional;
import loopwork.backend.recurringSession.RecurringSession;

import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(
        name = "client",
        uniqueConstraints = @UniqueConstraint(columnNames = {"professional_id", "email"})
)
public class Client {
    @Id
    // Auto-generated by JPA; omitted from the constructor on purpose
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column
    private String name;

    @Column()
    private String email;

    @Column
    private LocalDateTime createdAt;

    // Lazy fetch gives professional property just when it's explicity called
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "professional_id", nullable = false)
    private Professional professional;

    @OneToMany(mappedBy = "client", cascade = CascadeType.ALL, orphanRemoval = true)
    List<RecurringSession> recurringSessions;

    public Client(String name, String email, Professional professional) {
        this.name = name;
        this.email = email;
        this.professional = professional;
        this.createdAt = LocalDateTime.now();
    }

    public Client() { }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public Professional getProfessional() {
        return professional;
    }
}
