spring.datasource.url=jdbc:postgresql://localhost:5432/loopwork
spring.datasource.username=loopworkproject
spring.datasource.password=loopworkprojectpostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.loopwork=DEBUG