package loopwork.backend.professional;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "professional")
public class Professional {
    @Id
    // Auto-generated by JPA; omitted from the constructor on purpose
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column
    private String name;

    @Column(unique = true)
    private String email;

    @Column
    private String passwordHash;

    @Column
    private LocalDateTime createdAt;

    public Professional(String name, String email, String password) {
        this.name = name;
        this.email = email;
        this.passwordHash = password;
        this.createdAt = LocalDateTime.now();
    }

    public Professional() { }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setpasswordHash(String password) {
        this.passwordHash = password;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
